#!/bin/bash

#   ___  _             _      ____  ___
#  / _ \(_)  _____ ___| | /| / /  |/  /
# / , _/ / |/ / -_) __/ |/ |/ / /|_/ / 
#/_/|_/_/|___/\__/_/  |__/|__/_/  /_/  
#                                    

# -------------------------------------------
# variables
# ------------------------------------------- 

WALLPAPER="$HOME/wallpaper/downloads/uplspash_sky_1.jpg"
BROWSER="firefox"
TERMINAL="alacritty"
BACKGROUND_COLOR="0x000000"
ACTIVE_BORDER_COLOR="0x91f488"
INACTIVE_BORDER_COLOR="0x01b8dc"

BRIGHTNESS='notify-send -a System \
    -h string:wired-tag:system \
    -h int:value:$(echo $(brightnessctl get)00 / 255 | bc) \
    -t 1800 "Brightness $(echo $(brightnessctl get)00 / 255 | bc)%"'

VOLUME='notify-send -a System \
    -h string:wired-tag:system \
    -h int:value:$(pamixer --get-volume-human) \
    -t 1800 "Volume $(pamixer --get-volume-human)"'

VOLUME_TOGGLE='notify-send -a System \
    -h string:wired-tag:system \
    -t 1800 "Volume $(pamixer --get-volume-human)"'

# -------------------------------------------
# start Daemons
# -------------------------------------------

exec pipewire &
exec pipewire-pulse &
exec /usr/lib/kdeconnectd &
exec river-tag-overlay &
exec wired &
exec wbg $WALLPAPER &
exec waybar -s "$HOME/.config/waybar/style.css" -c "$HOME/.config/waybar/config" &
# swaybg -o eDP-1 -i "$WALLPAPER" -o HDMI-A-1 -i "$WALLPAPER" &

# -------------------------------------------
# settings
# -------------------------------------------

riverctl float-filter-add app-id "fzfrun"
riverctl float-filter-add app-id "kdeconnect-app"
riverctl float-filter-add app-id "qbittorrent"
riverctl float-filter-add app-id "zoom"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Set background and border color
riverctl background-color "$BACKGROUND_COLOR"
riverctl border-color-focused "$ACTIVE_BORDER_COLOR"
riverctl border-color-unfocused "$INACTIVE_BORDER_COLOR"

riverctl attach-mode top
riverctl set-cursor-warp on-output-change
riverctl focus-follows-cursor normal

# -------------------------------------------
# Keybindings
# -------------------------------------------

riverctl map normal Super Return spawn $TERMINAL
riverctl map normal Super G spawn $BROWSER
riverctl map normal Super N spawn "alacritty -e nnn -e"
riverctl map normal Super V spawn "alacritty -e nvim"

# toggle waybar
riverctl map normal Super B spawn "killall -SIGUSR1 waybar"

# custom fzf program launcher
riverctl map normal Super Space spawn "alacritty --class fzfrun -e ~/.dotfiles/scripts/fzfrun.sh"

# take partial and full screenshots
riverctl map normal Super P spawn "slurp | grim -g - ~/screenshots/$(date +'screenshot_%Y-%m-%d-%H%M%S.png')"
riverctl map normal None Print spawn "grim ~/screenshots/$(date +'screenshot_%Y-%m-%d-%H%M%S.png')"

riverctl map normal Super Q close
riverctl map normal Super+Shift Q exit

# switch focus between monitors
riverctl map normal Super Escape focus-output next
riverctl map normal Super+Shift Escape send-to-output next

# switch focus between views
riverctl map normal Super Tab focus-view next
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# swap views
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# resize and move floating views
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

# toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float
riverctl map normal Super S toggle-float

# toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do not have a modifier
for mode in normal locked
do
  # Eject the optical drive (well if you still have one that is)
  riverctl map $mode None XF86Eject spawn 'eject -T'

  riverctl map $mode None XF86AudioLowerVolume spawn "pamixer -d 5 && $VOLUME"
  riverctl map $mode None XF86AudioRaiseVolume spawn "pamixer -i 5 && $VOLUME"
  riverctl map $mode None XF86AudioMute spawn "pamixer --toggle-mute && $VOLUME_TOGGLE"

  riverctl map $mode Super F2 spawn "pamixer -d 5 && $VOLUME"
  riverctl map $mode Super F3 spawn "pamixer -i 5 && $VOLUME"
  riverctl map $mode Super F4 spawn "pamixer --toggle-mute && $VOLUME_TOGGLE"

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

  riverctl map $mode None XF86MonBrightnessUp spawn "brightnessctl s 5%+ && $BRIGHTNESS"
  riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl s 5%- && $BRIGHTNESS"

  riverctl map $mode Super F6 spawn "brightnessctl s 5%+ && $BRIGHTNESS"
  riverctl map $mode Super F5 spawn "brightnessctl s 5%- && $BRIGHTNESS"
done

for i in $(seq 1 9)
do
  tags=$((1 << ($i - 1)))

  # focus another tag
  riverctl map normal Super $i set-focused-tags $tags

  # move view between tags 
  riverctl map normal Super+Shift $i set-view-tags $tags

  # see compined view to 2 different tags 
  riverctl map normal Super+Control $i toggle-focused-tags $tags

  # make a view common for multiple tags
  riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 2 -main-ratio 0.5 -main-location left
